language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly

before_script: composer install --prefer-dist

script: phpunit --coverage-clover=app/logs/coverage.clover

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover app/logs/coverage.clover
