language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_install: printf "\n" | pecl install apcu-beta

before_script:
  - echo "apc.enable_cli=On" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install
