parameters:
    apiv1.routing.lazy_inflector.class: ApiV1Bundle\Service\Routing\LazyInflector

    apiv1.entity.ticket.class: ApiV1Bundle\Entity\Ticket
    apiv1.resource.ticket.class: ApiV1Bundle\Service\Resource\TicketResource

services:
    apiv1.routing.lazy_inflector:
        class: %apiv1.routing.lazy_inflector.class%

    apiv1.resource.ticket:
        class: %apiv1.resource.ticket.class%
        arguments: [@doctrine.orm.entity_manager, %apiv1.entity.ticket.class%]
