parameters:
    api.ticket.class: ApiV1Bundle\Entity\Ticket
    api.ticket.resource.class: ApiV1Bundle\Service\Resource\TicketResource

services:
    api.ticket.resource:
        class: %api.ticket.resource.class%
        arguments: [@doctrine.orm.entity_manager, %api.ticket.class%]
