parameters:
    apiv1.entity.ticket.class: ApiV1Bundle\Entity\Ticket
    apiv1.repository.ticket.class: ApiV1Bundle\Repository\TicketRepository
    apiv1.resource.ticket.class: ApiV1Bundle\Service\Resource\TicketResource

services:
    apiv1.repository.ticket:
        class: %apiv1.repository.ticket.class%
        factory: [@doctrine.orm.entity_manager, getRepository]
        arguments:
            - %apiv1.entity.ticket.class%

    apiv1.resource.ticket:
        class: %apiv1.resource.ticket.class%
        arguments: [@apiv1.repository.ticket, @validator]
