parameters:
    apiv1.lazy_inflector.class: ApiV1Bundle\Service\LazyInflector

    apiv1.ticket.class: ApiV1Bundle\Entity\Ticket
    apiv1.ticket.resource.class: ApiV1Bundle\Service\Resource\TicketResource

services:
    apiv1.lazy_inflector:
            class: %apiv1.lazy_inflector.class%

    apiv1.ticket.resource:
        class: %apiv1.ticket.resource.class%
        arguments: [@doctrine.orm.entity_manager, %apiv1.ticket.class%]
